Get by id/type account
jessiLeandro/stock-rp-api pull request #28
Opened 2021-02-08 13:28 UTC by guilhermestain

## Contexto
Foi criado a função getById em typeAccount.

## Checklist
- [ ] Rota.
- [ ] Controller.
- [ ] Domain

## Issues linkadas
- [ ] Resolves 53

## Como testar?

1. Baixar branch getById/typeAccount.
2. Testar fluxo de atualização de tipo de conta.

2021-02-10 00:16 UTC, novarealponto requested changes

2021-02-10 00:16 UTC, novarealponto commented on src/controllers/estoque/product/index.js
> +    const products = await productDomain.getById(req.query.id)
não é req.query temos que receber esse valor via params

2021-02-10 00:16 UTC, novarealponto commented on src/controllers/estoque/technician/index.js
> +    next(error)
mesmo caso do de cima

2021-02-10 00:16 UTC, novarealponto commented on src/controllers/typeAccount/index.js
> +        query = JSON.parse(req.query.query);
devemos usar ramda aqui e não fazer essas mudanças direto, atuar somente na issue, se precisar alterar devemos abrir uma issue para trabalhar nisso, inicialmente não estamos em refactor

2021-02-10 00:16 UTC, novarealponto commented on src/routes/protect/estoque/product.js
> +router.get("/getByIdProducts", productController.getByIdProducts)
dessa formar vamos conseguir pegar os dados via params no controller e domain
```suggestion
router.get("/getByIdProducts/:id", productController.getByIdProducts)
```

2021-02-10 00:16 UTC, novarealponto commented on src/routes/protect/estoque/technician.js
> +router.get("/getByIdTechnician", technicianController.getByIdTechnician)
mesmo caso do de cima

2021-02-10 00:16 UTC, novarealponto commented on src/routes/protect/typeAccount.js
> +router.get("/getByIdTypeAccount", typeAccountController.getByIdTypeAccount)
mesmo caso do de cima

2021-02-12 19:28 UTC, jessiLeandro approved these changes

2021-02-12 19:28 UTC, merged